/**
 * V2 Batch 4 — Tool Configurations (data-driven UI definitions).
 * Each entry maps directly to a backend engine in app/simulation/*:
 *   controls[].id  -> engine Input field name
 *   telemetry[].field -> engine Output field name
 */
window.V2_CONFIGS = {

  /* ───────────────────────── 1. Stress–Strain ───────────────────────── */
  "stress-strain": {
    title: "Stress–Strain & Elastic Constants",
    subtitle: "Python Mechanics Engine • Real-Time WebGL 3D • Hooke's Law, E, G, K, Elongation",
    category: "Strength of Materials",
    model: "stress_strain",
    ws: "stress-strain",
    schematicLabel: "Tensile Test Curve & Specimen",
    presets: true,
    anim: { mode: "scaleY", field: "elongation_mm", scale: 2.0 },
    controls: [
      { id: "applied_force_kn", label: "Tensile Force F", min: 1, max: 200, step: 1, value: 50, unit: "kN" },
      { id: "specimen_diameter_mm", label: "Diameter d", min: 5, max: 30, step: 0.5, value: 12.5, unit: "mm" },
      { id: "gauge_length_mm", label: "Gauge Length L", min: 10, max: 200, step: 5, value: 50, unit: "mm" },
      { id: "youngs_modulus_gpa", label: "Young's Modulus E", min: 20, max: 400, step: 10, value: 200, unit: "GPa" },
      { id: "poissons_ratio", label: "Poisson's Ratio ν", min: 0.1, max: 0.49, step: 0.01, value: 0.30 },
    ],
    telemetry: [
      { label: "Axial Stress σ", field: "axial_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Axial Strain ε", field: "axial_strain", fmt: (v) => (v * 1e6).toFixed(0) + " µε" },
      { label: "Elongation ΔL", field: "elongation_mm", fmt: (v) => v.toFixed(4) + " mm" },
      { label: "Shear Modulus G", field: "shear_modulus_gpa", fmt: (v) => v.toFixed(1) + " GPa" },
      { label: "Bulk Modulus K", field: "bulk_modulus_gpa", fmt: (v) => v.toFixed(1) + " GPa" },
    ],
    equation: { fmt: (d) => `σ = ${d.axial_stress_mpa.toFixed(1)} MPa | ε = ${(d.axial_strain*1e6).toFixed(0)} µε | G = ${d.shear_modulus_gpa.toFixed(1)} GPa, K = ${d.bulk_modulus_gpa.toFixed(1)} GPa` },
    draw2d: "stress-strain",
    explore: [
      { h: "1. Hooke's Law", p: "Within the elastic limit σ = E·ε. Stress is force per unit area; strain is the fractional elongation." },
      { h: "2. Elastic Constants", p: "G = E / 2(1+ν) and K = E / 3(1−2ν). Any two constants define the isotropic set." },
    ],
    practice: "<h3>Guided Experiment: Diameter vs Elongation</h3><p>Keep F = 50 kN, E = 200 GPa. Double d from 12.5→25 mm and observe area quadruples, dropping σ and ΔL by 4×.</p>",
    quiz: "<h3>Quiz: Max Poisson's ratio for an incompressible solid?</h3><p style='margin-top:8px'>✓ 0.50 (e.g., rubber, K→∞)</p>",
    related: [{ label: "Shaft Torsion", href: "/shaft-torsion.html" }, { label: "Column Buckling", href: "/column-buckling.html" }],
  },

  /* ───────────────────────── 2. Mohr's Circle ───────────────────────── */
  "mohrs-circle": {
    title: "Mohr's Circle of Stress",
    subtitle: "2D Principal Stresses • Max In-Plane Shear • Transformation at θ",
    category: "Strength of Materials",
    model: "mohrs_circle",
    ws: "mohrs-circle",
    schematicLabel: "Mohr's Circle (σ–τ Plane)",
    presets: true,
    controls: [
      { id: "sigma_x_mpa", label: "σₓ (MPa)", min: -500, max: 500, step: 5, value: 80, unit: "MPa" },
      { id: "sigma_y_mpa", label: "σᵧ (MPa)", min: -500, max: 500, step: 5, value: -40, unit: "MPa" },
      { id: "tau_xy_mpa", label: "τₓᵧ (MPa)", min: -500, max: 500, step: 5, value: 35, unit: "MPa" },
      { id: "arbitrary_theta_deg", label: "θ (deg)", min: -180, max: 180, step: 1, value: 30, unit: "°" },
    ],
    telemetry: [
      { label: "Principal σ₁", field: "principal_stress_1_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Principal σ₂", field: "principal_stress_2_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Max Shear τmax", field: "max_in_plane_shear_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "θp₁", field: "theta_p1_deg", fmt: (v) => v.toFixed(1) + "°" },
      { label: "Center σavg", field: "center_sigma_avg_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Radius R", field: "radius_r_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
    ],
    draw2d: "mohrs-circle",
    explore: [
      { h: "1. Circle Geometry", p: "Centre = (σavg, 0), Radius = √[((σₓ−σᵧ)/2)² + τₓᵧ²]. Points on the circle are stress states on rotated planes." },
      { h: "2. Principal Planes", p: "σ₁,₂ = σavg ± R occur at θp₁ = ½·atan2(2τₓᵧ, σₓ−σᵧ). Max shear planes are 45° from principal planes." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Set τₓᵧ = 0: the circle collapses to the line segment between σₓ and σᵧ — they are already principal stresses.</p>",
    quiz: "<h3>Quiz: Where does max in-plane shear act?</h3><p style='margin-top:8px'>✓ On planes oriented 45° from the principal planes.</p>",
    related: [{ label: "Stress–Strain", href: "/stress-strain.html" }, { label: "Pressure Vessel", href: "/pressure-vessel.html" }],
  },

  /* ───────────────────────── 3. Shaft Torsion ───────────────────────── */
  "shaft-torsion": {
    title: "Shaft Torsion",
    subtitle: "Polar Moment J • Shear Stress τ = T·r/J • Angle of Twist θ",
    category: "Strength of Materials",
    model: "shaft_torsion",
    ws: "shaft-torsion",
    schematicLabel: "Twisted Shaft & Shear Distribution",
    presets: true,
    controls: [
      { id: "shaft_type", label: "Shaft Type", type: "select", value: "solid", options: [{ value: "solid", label: "Solid" }, { value: "hollow", label: "Hollow" }] },
      { id: "outer_diameter_mm", label: "Outer Ø D", min: 10, max: 300, step: 1, value: 50, unit: "mm" },
      { id: "inner_diameter_mm", label: "Inner Ø d", min: 0, max: 250, step: 1, value: 0, unit: "mm" },
      { id: "shaft_length_m", label: "Length L", min: 0.2, max: 10, step: 0.1, value: 1.5, unit: "m" },
      { id: "applied_torque_nm", label: "Torque T", min: 10, max: 20000, step: 10, value: 1200, unit: "N·m" },
      { id: "rpm", label: "Speed N", min: 1, max: 8000, step: 10, value: 1500, unit: "rpm" },
      { id: "shear_modulus_gpa", label: "Shear Modulus G", min: 20, max: 120, step: 1, value: 79.3, unit: "GPa" },
    ],
    telemetry: [
      { label: "Polar Moment J", field: "polar_moment_j_mm4", fmt: (v) => v.toFixed(0) + " mm⁴" },
      { label: "Max Shear τ", field: "max_shear_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Twist Angle θ", field: "angle_of_twist_deg", fmt: (v) => v.toFixed(2) + "°" },
      { label: "Power P", field: "transmitted_power_kw", fmt: (v) => v.toFixed(2) + " kW" },
    ],
    draw2d: "shaft-torsion",
    explore: [
      { h: "1. Torsional Shear", p: "τ = T·r / J. Shear is zero at the axis and maximum at the outer surface." },
      { h: "2. Angle of Twist", p: "θ = T·L / (G·J). Hollow shafts give far better stiffness-to-weight than solid ones." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Switch Shaft Type to hollow and raise inner Ø: J barely drops while mass falls — explore the efficiency gain.</p>",
    quiz: "<h3>Quiz: Where is torsional shear maximum?</h3><p style='margin-top:8px'>✓ At the outer surface (r = R).</p>",
    related: [{ label: "Spring Design", href: "/spring-design.html" }, { label: "Stress–Strain", href: "/stress-strain.html" }],
  },

  /* ───────────────────────── 4. Column Buckling ───────────────────────── */
  "column-buckling": {
    title: "Column Buckling",
    subtitle: "Euler Critical Load • Rankine Formula • Slenderness Ratio",
    category: "Strength of Materials",
    model: "column_buckling",
    ws: "column-buckling",
    schematicLabel: "Buckled Column Mode Shape",
    presets: true,
    controls: [
      { id: "end_condition", label: "End Condition", type: "select", value: "pinned_pinned", options: [{ value: "pinned_pinned", label: "Pinned–Pinned (K=1)" }, { value: "fixed_fixed", label: "Fixed–Fixed (K=0.5)" }, { value: "fixed_free", label: "Fixed–Free (K=2)" }, { value: "fixed_pinned", label: "Fixed–Pinned (K=0.707)" }] },
      { id: "column_length_m", label: "Length L", min: 0.5, max: 12, step: 0.1, value: 3, unit: "m" },
      { id: "cross_section_type", label: "Section", type: "select", value: "rectangular", options: [{ value: "rectangular", label: "Rectangular" }, { value: "circular", label: "Circular" }] },
      { id: "width_mm", label: "Width b", min: 10, max: 400, step: 5, value: 80, unit: "mm" },
      { id: "depth_mm", label: "Depth h", min: 10, max: 400, step: 5, value: 120, unit: "mm" },
      { id: "youngs_modulus_gpa", label: "Young's Modulus E", min: 50, max: 400, step: 5, value: 200, unit: "GPa" },
      { id: "yield_strength_mpa", label: "Yield σy", min: 100, max: 800, step: 10, value: 250, unit: "MPa" },
    ],
    telemetry: [
      { label: "Effective Length Le", field: "effective_length_m", fmt: (v) => v.toFixed(2) + " m" },
      { label: "Slenderness λ", field: "slenderness_ratio", fmt: (v) => v.toFixed(0) },
      { label: "Euler Pcr", field: "euler_critical_load_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Rankine Pcr", field: "rankine_critical_load_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Critical Stress", field: "critical_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
    ],
    draw2d: "column-buckling",
    explore: [
      { h: "1. Euler's Law", p: "Pcr = π²EI / Le². Effective length Le = K·L depends on end restraint." },
      { h: "2. Rankine Formula", p: "1/P_R = 1/P_c + 1/P_E — valid for both slender and short columns." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Change end condition to Fixed–Free (K=2): Le doubles, Pcr drops to ¼ of the pinned case.</p>",
    quiz: "<h3>Quiz: Slenderness ratio λ = ?</h3><p style='margin-top:8px'>✓ Le / r, where r = √(I/A) is the radius of gyration.</p>",
    related: [{ label: "Mohr's Circle", href: "/mohrs-circle.html" }, { label: "Truss Analysis", href: "/truss-analysis.html" }],
  },

  /* ───────────────────────── 5. Pressure Vessel ───────────────────────── */
  "pressure-vessel": {
    title: "Thin Pressure Vessel",
    subtitle: "Hoop Stress σh = p·d/2t • Longitudinal Stress • Max Shear",
    category: "Strength of Materials",
    model: "pressure_vessel",
    ws: "pressure-vessel",
    schematicLabel: "Cylinder Stress Elements",
    presets: true,
    controls: [
      { id: "vessel_category", label: "Category", type: "select", value: "thin_cylinder", options: [{ value: "thin_cylinder", label: "Thin Cylinder" }, { value: "thin_sphere", label: "Thin Sphere" }, { value: "thick_cylinder", label: "Thick Cylinder" }] },
      { id: "internal_pressure_bar", label: "Pressure p", min: 1, max: 500, step: 1, value: 20, unit: "bar" },
      { id: "inner_diameter_mm", label: "Inner Ø d", min: 50, max: 3000, step: 10, value: 400, unit: "mm" },
      { id: "wall_thickness_mm", label: "Wall t", min: 1, max: 100, step: 1, value: 10, unit: "mm" },
      { id: "joint_efficiency_eta", label: "Joint η", min: 0.5, max: 1, step: 0.01, value: 0.85 },
    ],
    telemetry: [
      { label: "Hoop Stress σh", field: "hoop_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Longitudinal σL", field: "longitudinal_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Max Shear τmax", field: "max_shear_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Volumetric Strain", field: "volumetric_strain", fmt: (v) => v.toExponential(2) },
    ],
    draw2d: "pressure-vessel",
    explore: [
      { h: "1. Hoop vs Longitudinal", p: "For a thin cylinder σh = p·d/(2t) is twice σL = p·d/(4t). Hoop stress governs the design." },
      { h: "2. Joint Efficiency", p: "η reduces the effective plate strength at riveted/welded seams — always factor it into σallow." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Double wall thickness t: both σh and σL halve. Watch the 2:1 ratio stay constant.</p>",
    quiz: "<h3>Quiz: Which stress is larger in a cylindrical vessel?</h3><p style='margin-top:8px'>✓ Hoop stress (2× longitudinal).</p>",
    related: [{ label: "Mohr's Circle", href: "/mohrs-circle.html" }, { label: "Weld Strength", href: "/weld-strength.html" }],
  },

  /* ───────────────────────── 6. Spring Design ───────────────────────── */
  "spring-design": {
    title: "Helical Spring Design",
    subtitle: "Wahl Factor Kw • Shear Stress • Deflection & Spring Rate",
    category: "Strength of Materials",
    model: "spring_design",
    ws: "spring-design",
    schematicLabel: "Helical Coil Spring",
    presets: true,
    anim: { mode: "scaleY", field: "deflection_mm", scale: -0.01 },
    controls: [
      { id: "applied_load_n", label: "Load P", min: 10, max: 5000, step: 10, value: 800, unit: "N" },
      { id: "wire_diameter_mm", label: "Wire Ø d", min: 1, max: 30, step: 0.5, value: 6, unit: "mm" },
      { id: "mean_coil_diameter_mm", label: "Mean Ø D", min: 5, max: 200, step: 1, value: 48, unit: "mm" },
      { id: "active_coils", label: "Active Coils n", min: 2, max: 30, step: 1, value: 8 },
      { id: "shear_modulus_gpa", label: "Shear Modulus G", min: 30, max: 120, step: 1, value: 79.3, unit: "GPa" },
    ],
    telemetry: [
      { label: "Spring Index C", field: "spring_index_c", fmt: (v) => v.toFixed(2) },
      { label: "Wahl Factor Kw", field: "wahl_factor_kw", fmt: (v) => v.toFixed(3) },
      { label: "Shear Stress τ", field: "max_shear_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Deflection δ", field: "deflection_mm", fmt: (v) => v.toFixed(2) + " mm" },
      { label: "Spring Rate k", field: "spring_rate_n_mm", fmt: (v) => v.toFixed(2) + " N/mm" },
    ],
    draw2d: "spring-design",
    explore: [
      { h: "1. Wahl Correction", p: "Kw = (4C−1)/(4C−4) + 0.615/C accounts for direct shear & curvature in close-coiled springs." },
      { h: "2. Deflection", p: "δ = 8PD³n / (Gd⁴). Rate k = P/δ increases sharply with wire diameter." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Increase active coils n: deflection grows linearly, spring becomes softer (lower k).</p>",
    quiz: "<h3>Quiz: What does the Wahl factor correct for?</h3><p style='margin-top:8px'>✓ Curvature & direct shear effects ignored by the basic torsion formula.</p>",
    related: [{ label: "Shaft Torsion", href: "/shaft-torsion.html" }, { label: "Bolted Joint", href: "/bolted-joint.html" }],
  },

  /* ───────────────────────── 7. Bolted Joint ───────────────────────── */
  "bolted-joint": {
    title: "Bolted Joint Design",
    subtitle: "Preload • Clamping Force • Tightening Torque T = K·Fi·d",
    category: "Strength of Materials",
    model: "bolted_joint",
    ws: "bolted-joint",
    schematicLabel: "Bolt–Nut–Clamped Plate Assembly",
    presets: true,
    controls: [
      { id: "bolt_nominal_dia_mm", label: "Bolt Ø d", min: 6, max: 48, step: 1, value: 16, unit: "mm" },
      { id: "property_class", label: "Property Class", type: "select", value: "8.8", options: [{ value: "8.8", label: "Grade 8.8 (580 MPa)" }, { value: "10.9", label: "Grade 10.9 (830 MPa)" }] },
      { id: "applied_tensile_kn", label: "Applied Tensile F", min: 1, max: 300, step: 1, value: 35, unit: "kN" },
      { id: "torque_coefficient_k", label: "Torque Coeff K", min: 0.1, max: 0.3, step: 0.01, value: 0.20 },
    ],
    telemetry: [
      { label: "Proof Strength", field: "proof_strength_mpa", fmt: (v) => v.toFixed(0) + " MPa" },
      { label: "Preload Fi", field: "preload_force_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Clamping Force", field: "remaining_clamping_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Bolt Stress σb", field: "bolt_tensile_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Tightening Torque", field: "tightening_torque_nm", fmt: (v) => v.toFixed(1) + " N·m" },
    ],
    draw2d: "bolted-joint",
    explore: [
      { h: "1. Preload", p: "Fi = 0.75·Sp·At. Preload keeps the joint closed and carries most of the external load via joint stiffness." },
      { h: "2. Tightening Torque", p: "T = K·Fi·d. Only ~10% of torque stretches the bolt; the rest overcomes friction." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Raise applied tensile load: clamping force drops but bolt load rises only by the joint stiffness fraction C.</p>",
    quiz: "<h3>Quiz: Why preload a bolt?</h3><p style='margin-top:8px'>✓ To keep the joint sealed/closed and limit fatigue by reducing cyclic bolt load.</p>",
    related: [{ label: "Riveted Joints", href: "/riveted-joints.html" }, { label: "Spring Design", href: "/spring-design.html" }],
  },

  /* ───────────────────────── 8. Riveted Joints ───────────────────────── */
  "riveted-joints": {
    title: "Riveted Joint Analysis",
    subtitle: "Tearing • Shearing • Crushing • Joint Efficiency η",
    category: "Strength of Materials",
    model: "riveted_joints",
    ws: "riveted-joints",
    schematicLabel: "Lap / Butt Riveted Joint",
    presets: true,
    controls: [
      { id: "joint_type", label: "Joint Type", type: "select", value: "butt_double_strap", options: [{ value: "lap_single_rivet", label: "Lap (single rivet)" }, { value: "butt_single_strap", label: "Butt (single strap)" }, { value: "butt_double_strap", label: "Butt (double strap)" }] },
      { id: "plate_thickness_mm", label: "Plate t", min: 2, max: 40, step: 1, value: 12, unit: "mm" },
      { id: "rivet_diameter_mm", label: "Rivet Ø d", min: 5, max: 40, step: 1, value: 22, unit: "mm" },
      { id: "pitch_distance_mm", label: "Pitch p", min: 20, max: 200, step: 1, value: 70, unit: "mm" },
      { id: "permissible_tensile_mpa", label: "σt allow", min: 50, max: 250, step: 5, value: 120, unit: "MPa" },
      { id: "permissible_shear_mpa", label: "τ allow", min: 40, max: 200, step: 5, value: 95, unit: "MPa" },
      { id: "permissible_crushing_mpa", label: "σc allow", min: 80, max: 300, step: 5, value: 160, unit: "MPa" },
    ],
    telemetry: [
      { label: "Joint Efficiency η", field: "joint_efficiency_pct", fmt: (v) => v.toFixed(1) + " %" },
      { label: "Governing Mode", field: "governing_mode", fmt: (v) => v },
      { label: "Tearing Strength", field: "plate_tearing_strength_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Shearing Strength", field: "rivet_shearing_strength_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Crushing Strength", field: "rivet_crushing_strength_kn", fmt: (v) => v.toFixed(1) + " kN" },
    ],
    draw2d: "riveted-joints",
    explore: [
      { h: "1. Three Failure Modes", p: "A riveted joint may fail by plate tearing (p−d)·t·σt, rivet shear, or rivet/plate crushing." },
      { h: "2. Efficiency", p: "η = (least strength / solid plate strength) × 100%. Design the pitch to balance all three." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Reduce pitch p toward d: tearing strength falls, efficiency drops — find the optimum pitch ≈ 3d.</p>",
    quiz: "<h3>Quiz: Which joint gives highest efficiency?</h3><p style='margin-top:8px'>✓ Double-cover butt joint (2 shear planes, 2 rivets per pitch).</p>",
    related: [{ label: "Rivet Designer", href: "/rivet-joint-designer.html" }, { label: "Bolted Joint", href: "/bolted-joint.html" }],
  },

  /* ───────────────────────── 9. Rivet Joint Designer ───────────────────────── */
  "rivet-joint-designer": {
    title: "Rivet Joint Designer",
    subtitle: "Pitch • Margin • Multi-Row Layout Optimizer",
    category: "Strength of Materials",
    model: "rivet_joint_designer",
    ws: "rivet-joint-designer",
    schematicLabel: "Rivet Layout Grid (Pitch & Margin)",
    presets: true,
    controls: [
      { id: "joint_type", label: "Joint Type", type: "select", value: "lap_double", options: [{ value: "lap_single", label: "Lap (single row)" }, { value: "lap_double", label: "Lap (double row)" }, { value: "butt_single_strap", label: "Butt (single strap)" }, { value: "butt_double_strap", label: "Butt (double strap)" }] },
      { id: "plate_thickness_mm", label: "Plate t", min: 2, max: 40, step: 1, value: 12, unit: "mm" },
      { id: "rivet_diameter_mm", label: "Rivet Ø d", min: 5, max: 40, step: 1, value: 22, unit: "mm" },
      { id: "plate_width_mm", label: "Plate Width b", min: 60, max: 800, step: 10, value: 200, unit: "mm" },
      { id: "applied_force_kn", label: "Load P", min: 10, max: 3000, step: 10, value: 300, unit: "kN" },
      { id: "num_rows", label: "Rows", min: 1, max: 4, step: 1, value: 2 },
      { id: "safety_factor", label: "Safety Factor", min: 1, max: 6, step: 0.5, value: 2 },
    ],
    telemetry: [
      { label: "Recommended Pitch p", field: "recommended_pitch_mm", fmt: (v) => v.toFixed(0) + " mm" },
      { label: "Recommended Margin m", field: "recommended_margin_mm", fmt: (v) => v.toFixed(0) + " mm" },
      { label: "Rivets / Row", field: "rivets_per_row", fmt: (v) => v + "" },
      { label: "Joint Efficiency η", field: "joint_efficiency_pct", fmt: (v) => v.toFixed(1) + " %" },
      { label: "Governing Mode", field: "governing_mode", fmt: (v) => v },
    ],
    draw2d: "rivet-joint-designer",
    explore: [
      { h: "1. Pitch & Margin Rules", p: "Code rule of thumb: pitch p ≈ 3d, edge margin m ≈ 1.5d to prevent shearing of the plate edge." },
      { h: "2. Multi-Row Layout", p: "Adding rows multiplies shear planes — increasing both strength and achievable efficiency." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Increase number of rows: required rivets/row drops and joint efficiency rises toward the governing limit.</p>",
    quiz: "<h3>Quiz: Why keep margin m ≈ 1.5d?</h3><p style='margin-top:8px'>✓ To prevent the plate from tearing out at the free edge between rivets.</p>",
    related: [{ label: "Riveted Joints", href: "/riveted-joints.html" }, { label: "Weld Strength", href: "/weld-strength.html" }],
  },

  /* ───────────────────────── 10. Weld Strength ───────────────────────── */
  "weld-strength": {
    title: "Weld Strength Analysis",
    subtitle: "Throat Thickness • Allowable Load • Factor of Safety",
    category: "Strength of Materials",
    model: "weld_strength",
    ws: "weld-strength",
    schematicLabel: "Fillet / Butt Weld Section",
    presets: true,
    controls: [
      { id: "weld_type", label: "Weld Type", type: "select", value: "double_parallel_fillet", options: [{ value: "single_transverse_fillet", label: "Single Transverse Fillet" }, { value: "double_transverse_fillet", label: "Double Transverse Fillet" }, { value: "double_parallel_fillet", label: "Double Parallel Fillet" }, { value: "butt_weld", label: "Butt Weld" }] },
      { id: "weld_size_mm", label: "Leg Size s", min: 1, max: 30, step: 0.5, value: 8, unit: "mm" },
      { id: "weld_length_mm", label: "Length l", min: 10, max: 800, step: 5, value: 100, unit: "mm" },
      { id: "applied_force_kn", label: "Load F", min: 1, max: 400, step: 1, value: 60, unit: "kN" },
      { id: "allowable_shear_mpa", label: "τ allow", min: 40, max: 200, step: 5, value: 95, unit: "MPa" },
    ],
    telemetry: [
      { label: "Throat t = 0.707s", field: "throat_thickness_mm", fmt: (v) => v.toFixed(2) + " mm" },
      { label: "Allowable Load", field: "allowable_load_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Actual Shear τ", field: "actual_shear_stress_mpa", fmt: (v) => v.toFixed(1) + " MPa" },
      { label: "Factor of Safety", field: "weld_safety_factor", fmt: (v) => v.toFixed(2) },
    ],
    draw2d: "weld-strength",
    explore: [
      { h: "1. Throat of Fillet", p: "Effective throat = 0.707 × leg size s. Strength is based on this minimum cross-section." },
      { h: "2. Parallel vs Transverse", p: "Parallel fillets carry load along their length; transverse fillets resist load perpendicular to the weld." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Switch from single to double parallel fillet: effective area doubles, allowable load doubles.</p>",
    quiz: "<h3>Quiz: Throat thickness of a fillet weld?</h3><p style='margin-top:8px'>✓ 0.707 × leg size.</p>",
    related: [{ label: "Riveted Joints", href: "/riveted-joints.html" }, { label: "Pressure Vessel", href: "/pressure-vessel.html" }],
  },

  /* ───────────────────────── 11. Crack Propagation ───────────────────────── */
  "crack-propagation": {
    title: "Crack Propagation (LEFM)",
    subtitle: "Stress Intensity KI • Critical Crack Size • Paris Law Life",
    category: "Strength of Materials",
    model: "crack_propagation",
    ws: "crack-propagation",
    schematicLabel: "Edge-Cracked Plate & KI",
    presets: true,
    controls: [
      { id: "initial_crack_size_mm", label: "Initial a₀", min: 0.1, max: 30, step: 0.1, value: 2, unit: "mm" },
      { id: "fracture_toughness_mpam", label: "KIC", min: 10, max: 200, step: 1, value: 50, unit: "MPa√m" },
      { id: "max_stress_mpa", label: "σmax", min: 20, max: 800, step: 5, value: 150, unit: "MPa" },
      { id: "min_stress_mpa", label: "σmin", min: 0, max: 400, step: 5, value: 0, unit: "MPa" },
      { id: "paris_constant_c", label: "Paris C", min: 0.00000000000001, max: 0.0000000001, step: 0.00000000000001, value: 0.00000000001 },
      { id: "paris_exponent_m", label: "Paris m", min: 2, max: 5, step: 0.1, value: 3 },
    ],
    telemetry: [
      { label: "Stress Intensity KI", field: "stress_intensity_ki_mpam", fmt: (v) => v.toFixed(2) + " MPa√m" },
      { label: "Critical Size ac", field: "critical_crack_size_mm", fmt: (v) => v.toFixed(2) + " mm" },
      { label: "Cycles to Failure Nf", field: "cycles_to_failure_nf", fmt: (v) => Math.round(v).toLocaleString() },
    ],
    draw2d: "crack-propagation",
    explore: [
      { h: "1. Stress Intensity", p: "KI = 1.12·σ·√(πa). Failure occurs when KI reaches the material toughness KIC." },
      { h: "2. Paris Law", p: "da/dN = C·(ΔK)^m. Integrating gives the fatigue crack growth life to the critical size." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Raise σmax toward KIC/ (1.12√πa): ac shrinks and life Nf collapses dramatically.</p>",
    quiz: "<h3>Quiz: Failure criterion in LEFM?</h3><p style='margin-top:8px'>✓ KI ≥ KIC — the stress intensity reaches fracture toughness.</p>",
    related: [{ label: "Bolted Joint", href: "/bolted-joint.html" }, { label: "Mohr's Circle", href: "/mohrs-circle.html" }],
  },

  /* ───────────────────────── 12. Truss Analysis ───────────────────────── */
  "truss-analysis": {
    title: "Truss Structural Analysis",
    subtitle: "Method of Joints • Reactions • Tension/Compression",
    category: "Strength of Materials",
    model: "truss_structural_analysis",
    ws: "truss-analysis",
    schematicLabel: "Plane Pin-Jointed Truss",
    presets: true,
    controls: [
      { id: "truss_type", label: "Truss Type", type: "select", value: "pratt_bridge", options: [{ value: "pratt_bridge", label: "Pratt Bridge" }, { value: "howe_roof", label: "Howe Roof" }, { value: "warren_truss", label: "Warren Truss" }] },
      { id: "span_length_m", label: "Span L", min: 4, max: 40, step: 1, value: 12, unit: "m" },
      { id: "height_h_m", label: "Height H", min: 1, max: 12, step: 0.5, value: 3, unit: "m" },
      { id: "applied_load_kn", label: "Joint Load P", min: 5, max: 400, step: 5, value: 50, unit: "kN" },
    ],
    telemetry: [
      { label: "Reaction Ay", field: "left_reaction_ay_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Reaction By", field: "right_reaction_by_kn", fmt: (v) => v.toFixed(1) + " kN" },
      { label: "Max Compression", field: "max_compression_force_kn", fmt: (v) => v.toFixed(1) + " kN (C)" },
      { label: "Max Tension", field: "max_tension_force_kn", fmt: (v) => v.toFixed(1) + " kN (T)" },
      { label: "Zero-Force Members", field: "zero_force_members_count", fmt: (v) => v + "" },
    ],
    draw2d: "truss-analysis",
    explore: [
      { h: "1. Method of Joints", p: "Isolate each pin joint; ΣFx = 0, ΣFy = 0 yields member axial forces." },
      { h: "2. Tension vs Compression", p: "Top chord carries compression, bottom chord carries tension under gravity loading." },
    ],
    practice: "<h3>Guided Experiment</h3><p>Compare Pratt vs Howe: diagonal roles swap — Pratt diagonals go into tension under gravity.</p>",
    quiz: "<h3>Quiz: How many zero-force members in a Warren truss?</h3><p style='margin-top:8px'>✓ Typically 1 for the standard symmetric case modelled here.</p>",
    related: [{ label: "Column Buckling", href: "/column-buckling.html" }, { label: "Riveted Joints", href: "/riveted-joints.html" }],
  },
};
